version: "3.7"
services: 
  database_rentx1:
    image: postgres
    container_name: database_rentx1
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentx1
    volumes: 
      - pgdata:/data/postgres
    network_mode: "host"

  app:
    build: .
    container_name: rentx1
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    network_mode: "host"

volumes: 
  pgdata:
    driver: local
