name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
         node-version: 12.x
    
    # - Instalar as dependências     
    - name: Install dependencies
      run: yarn    
    
    # - Executar a build
    - name: Run build
      run: yarn build
    
    # - Copiar código para AWS
    - name: Copy dist to aws
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/sua_aplicacao"
    
    # - Run production scripts tu run yarn, migrations and restart service    
    - name: Install dependencies on AWS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/sua_aplicao
          yarn
          ./node_modules/.bin/typeorm migration:run
          pm2 restart sua_aplicao
    
    
    
  
